version: '3'
services:
  app:
    container_name: IncidentSystem
    restart: always
    build: .
    ports:
      - '3001:3001'
    command: npm run start:debug
    volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
    links:
      - mongo
  
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - '27017:27017'